name: "Automatically check for updates and open a PR"

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check For Updates
        id: check
        run: |
          if ./check-update.sh --update-lockfile; then
            echo "::set-output name=update_available::${{ toJSON(true) }}"
          else
            echo "::set-output name=update_available::${{ toJSON(false) }}"
          fi

      - name: Perform Updates
        if: ${{ fromJSON(steps.check.outputs.update_available) }}
        run: |
          git config user.email "andrew@du.nham.ca"
          git config user.name "Andrew Dunham"
          ./update.sh
          
          printf "\nCommits:\n"
          git log --oneline $(git merge-base --fork-point main)..HEAD
          printf "\nDiff:\n"
          git diff $(git merge-base --fork-point main)

      - name: Create Pull Request
        if: ${{ fromJSON(steps.check.outputs.update_available) }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GH_REPO_TOKEN}}
          assignees: andrew-d
          delete-branch: true
          branch: auto-version-bump/bump
          branch-suffix: timestamp
          base: main
          title: "Bump Versions"
